language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3
jobs:
  include:
    - name: "Python: 2.7, pure (no C extensions)"
      python: 2.7
      env: PURE_PYTHON=1
install:
  - pip install -U pip setuptools
  - pip install -U coverage coveralls
  - pip install -U -e .[test]
  - if [[ $PURE_PYTHON ]]; then pip install -U -e .[zodb,zcml]; fi
script:
  - coverage run -m zope.testrunner --test-path=src
after_success:
  - coveralls
notifications:
  email: false
cache: pip
